version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_file_server
    volumes:
      - ./data:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
